const COLORS = {
    light: {
      primary: '#6C63FF',
      secondary: '#4ECDC4',
      accent: '#FF6B6B',
      success: '#2ECC71',
      warning: '#FF0000',
      danger: '#F25F5C',
      info: '#45B7D1',
      light: '#F8F9FA',
      dark: '#343A40',
      white: '#FFFFFF',
      teal: '#20C997',
      landmarkColors: { default: '#FFFFFF' },
    },
    dark: {
      primary: '#6C63FF',
      secondary: '#4ECDC4',
      accent: '#FF6B6B',
      success: '#2ECC71',
      warning: '#FF0000',
      danger: '#F25F5C',
      info: '#45B7D1',
      light: '#2C2F33',
      dark: '#FFFFFF',
      white: '#1E2124',
      teal: '#20C997',
      landmarkColors: { default: '#FFFFFF' },
    },
  };