import { StyleSheet, Dimensions } from 'react-native';

// Screen width for responsive design
const SCREEN_WIDTH = Dimensions.get('window').width;
const { height } = Dimensions.get('window');

const getStyles = (COLORS, SHADOWS) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#000',
    },
    safeArea: {
      flex: 1,
      backgroundColor: '#000', // StatusBar ile uyumlu bir arka plan rengi
    },
    headerContainer: {
      height: 60, // Hayali header yüksekliği
      backgroundColor: '#000', // Arka planla aynı renk
      justifyContent: 'center', // Dikeyde dil filtresi için alan
      paddingHorizontal: 10, // Sol ve sağdan boşluk
    },
    languageContainer: {
      alignItems: 'flex-start', // Sola hizalama
    },
    main: {
      padding: 18,
      width: '100%',
      alignItems: 'center',
    },
    stepContainer: {
      marginBottom: 25,
      width: '100%',
      paddingHorizontal: 15,
      alignItems: 'center',
    },
    scrollView: {
      flex: 1,
    },
    stepTitle: {
      fontSize: 22,
      textAlign: 'center',
      marginBottom: 24,
      color: COLORS.dark,
      fontWeight: 'bold',
      letterSpacing: 0.5,
    },
    uploadContainer: {
      marginBottom: 25,
      width: '100%',
      alignItems: 'center',
    },
    buttonRow: {
      flexDirection: 'column', // Changed from 'row' to 'column'
      justifyContent: 'center',
      gap: 15, // Increased gap for better spacing between stacked buttons
      width: '100%',
      alignItems: 'center', // Center the buttons horizontally
    },
    actionButton: {
      backgroundColor: COLORS.primary,
      paddingVertical: 12, // Increased from 8
      paddingHorizontal: 15,
      borderRadius: 25,
      width: SCREEN_WIDTH * 0.8, // Changed from minWidth to width and increased to 80% of screen
      alignItems: 'center',
      justifyContent: 'center',
      ...SHADOWS.colored,
      marginBottom: 5, // Add some margin at the bottom
    },
    actionButtonText: {
      color: COLORS.white,
      fontSize: 16, // Increased from 14
      fontWeight: 'bold',
      textAlign: 'center',
      padding: 4, // Added padding to make text more prominent
    },
    continueButton: {
      backgroundColor: COLORS.success,
      paddingVertical: 15,
      paddingHorizontal: 30,
      borderRadius: 50,
      minWidth: SCREEN_WIDTH * 0.4,
      alignItems: 'center',
      ...SHADOWS.medium,
    },
    backButton: {
      backgroundColor: COLORS.accent,
      paddingVertical: 15,
      paddingHorizontal: 30,
      borderRadius: 50,
      minWidth: 100,
      alignItems: 'center',
      ...SHADOWS.accent,
    },
    buttonText: {
      color: '#fff',
      fontSize: Math.min(16, SCREEN_WIDTH * 0.04),
      fontWeight: 'bold',
      textAlign: 'center',
    },
    imageContainer: {
      width: '100%',
      alignItems: 'center',
      marginVertical: 15,
    },
    image: {
      borderRadius: 20,
      ...SHADOWS.medium,
      borderWidth: 3,
      borderColor: COLORS.dark,
    },
    progressContainer: {
      margin: 25,
      width: '90%',
      alignSelf: 'center',
    },
    progressBarBackground: {
      height: 15,
      backgroundColor: 'rgba(108, 99, 255, 0.2)',
      borderRadius: 10,
      overflow: 'hidden',
    },
    progressBar: {
      height: '100%',
      backgroundColor: COLORS.primary,
      borderRadius: 10,
    },
    progressText: {
      textAlign: 'center',
      fontSize: 16,
      color: COLORS.dark,
      fontWeight: '600',
      marginTop: 8,
    },
    analysisContainer: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 30,
      width: '100%',
    },
    analysisItem: {
      width: '100%',
      marginBottom: 25,
      backgroundColor: COLORS.white,
      borderRadius: 20,
      padding: 15,
      ...SHADOWS.small,
    },
    analysisTitle: {
      textAlign: 'center',
      marginBottom: 15,
      color: COLORS.primary,
      fontSize: 20,
      fontWeight: 'bold',
    },
    imageWrapper: {
      position: 'relative',
      width: 300,
      height: 300,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 20,
      overflow: 'hidden',
    },
    svgOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
    },
    loadingOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(44, 47, 51, 0.85)',
      borderRadius: 15,
    },
    loadingText: {
      color: COLORS.dark,
      fontSize: 20,
      marginTop: 15,
      fontWeight: 'bold',
    },
    compatibilityCard: {
      backgroundColor: 'rgba(108, 99, 255, 0.2)',
      borderRadius: 15,
      padding: 15,
      marginBottom: 15,
      ...SHADOWS.small,
    },
    compatibilityTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: COLORS.dark,
      textAlign: 'center',
      marginBottom: 10,
    },
    compatibilityScoreContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    compatibilityImage: {
      width: 50,
      height: 50,
      borderRadius: 25,
      borderWidth: 2,
      borderColor: COLORS.dark,
    },
    compatibilityScoreText: {
      fontSize: 24,
      fontWeight: 'bold',
    },
    compatibilityMessage: {
      fontSize: 14,
      color: COLORS.dark,
      textAlign: 'center',
      lineHeight: 20,
    },
    detailCard: {
      backgroundColor: COLORS.white,
      borderRadius: 15,
      padding: 15,
      marginBottom: 12,
      borderLeftWidth: 4,
      borderLeftColor: COLORS.primary,
      ...SHADOWS.small,
    },
    detailCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    detailCardTitle: {
      fontSize: 16,
      fontWeight: 'bold',
      color: COLORS.dark,
      flex: 1,
    },
    detailCardScore: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    detailCardDescription: {
      fontSize: 14,
      color: COLORS.dark,
      marginTop: 8,
      lineHeight: 20,
    },
    fullWidthImage: {
      width: '100%',
      height: 200,
      borderRadius: 15,
      marginVertical: 12,
      ...SHADOWS.small,
    },
    infoCard: {
      backgroundColor: COLORS.white,
      borderRadius: 15,
      padding: 15,
      marginBottom: 15,
      ...SHADOWS.small,
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    infoLabel: {
      fontSize: 16,
      fontWeight: 'bold',
      color: COLORS.dark,
    },
    infoValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: COLORS.primary,
    },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 20,
      width: '100%',
      gap: 10,
    },
    greenButton: {
      backgroundColor: COLORS.success,
      borderRadius: 10,
      paddingVertical: 15,
      marginVertical: 10,
      alignItems: 'center',
      ...SHADOWS.medium,
      flex: 1,
    },
    redButton: {
      backgroundColor: COLORS.danger,
      borderRadius: 10,
      paddingVertical: 15,
      marginVertical: 10,
      alignItems: 'center',
      ...SHADOWS.medium,
      flex: 1,
    },
    unlockButton: {
      backgroundColor: COLORS.primary,
      borderRadius: 10,
      paddingVertical: 15,
      marginVertical: 10,
      alignItems: 'center',
      ...SHADOWS.medium,
      flex: 1,
      borderWidth: 2,
      borderColor: COLORS.accent,
    },
    errorText: {
      color: COLORS.danger,
      textAlign: 'center',
      fontSize: 16,
      backgroundColor: 'rgba(242, 95, 92, 0.2)',
      padding: 10,
      borderRadius: 10,
      marginVertical: 10,
      fontWeight: 'bold',
    },
    warningText: {
      color: COLORS.warning,
      textAlign: 'center',
      fontSize: 16,
      backgroundColor: 'rgba(255, 0, 0, 0.23)',
      padding: 10,
      borderRadius: 10,
      marginVertical: 10,
      fontStyle: 'italic',
    },
    teaserText: {
      fontSize: Math.min(16, SCREEN_WIDTH * 0.04),
      color: '#7B31FF',
      textAlign: 'center',
      marginVertical: 15,
      fontStyle: 'italic',
      fontWeight: '600',
      paddingHorizontal: 20,
    },
    resultsHeader: {
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 10,
    },
    eyesIcon: {
      fontSize: 32,
      marginBottom: 10,
      color: '#fff',
    },
    resultsTitle: {
      fontSize: Math.min(36, SCREEN_WIDTH * 0.09),
      fontWeight: 'bold',
      color: '#fff',
      textAlign: 'center',
      marginBottom: 10,
    },
    resultsSubtitle: {
      fontSize: Math.min(18, SCREEN_WIDTH * 0.045),
      color: '#fff',
      textAlign: 'center',
      marginBottom: 20,
      paddingHorizontal: 20,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    imagesContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      marginBottom: 15,
    },
    imageWithLabel: {
      alignItems: 'center',
      width: '40%',
      maxWidth: 150,
    },
    circularImage: {
      width: SCREEN_WIDTH * 0.25,
      height: SCREEN_WIDTH * 0.25,
      maxWidth: 100,
      maxHeight: 100,
      borderRadius: SCREEN_WIDTH * 0.125,
      borderWidth: 3,
      borderColor: '#fff',
      marginBottom: 5,
    },
    imageLabel: {
      color: '#fff',
      fontSize: Math.min(14, SCREEN_WIDTH * 0.035),
      fontWeight: 'bold',
      textAlign: 'center',
      width: '100%',
    },
    blurredCategories: {
      width: '100%',
      marginTop: 5,
      marginBottom: 20,
      paddingHorizontal: 10,
    },
    categoryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
      width: '100%',
    },
    categoryColumn: {
      alignItems: 'center',
      width: '48%',
    },
    categoryTitleSmall: {
      color: '#fff',
      fontSize: Math.min(16, SCREEN_WIDTH * 0.04),
      textAlign: 'center',
      marginBottom: 5,
    },
    blurredScoreContainer: {
      width: 60,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      position: 'relative',
      overflow: 'hidden',
      borderRadius: 15,
    },
    blurredScore: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    blurredContent: {
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: 15,
    },
    fakeBlurOverlay: {
      position: 'absolute',
      width: '20%',
      height: '20%',
      backgroundColor: 'rgb(255, 255, 255)',
      borderRadius: 15,
      opacity: 0.2,
      shadowColor: '#fff',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.9,
      shadowRadius: 18,
      elevation: 4,
    },
    scoreProgressBar: {
      width: '90%',
      height: 6,
      backgroundColor: '#444',
      borderRadius: 3,
      overflow: 'hidden',
    },
    scoreProgress: {
      height: '100%',
      backgroundColor: '#888',
      borderRadius: 3,
    },
    actionsButtonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: '5%',
      width: '100%',
      marginBottom: 20,
    },
    getProButton: {
      backgroundColor: '#7B31FF',
      paddingVertical: Math.min(15, SCREEN_WIDTH * 0.035),
      paddingHorizontal: Math.min(20, SCREEN_WIDTH * 0.04),
      borderRadius: 50,
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      marginRight: 10,
      ...SHADOWS.medium,
      borderWidth: 2,
      borderColor: '#fff',
    },
    inviteFriendsButton: {
      backgroundColor: '#000',
      borderRadius: 50,
      borderWidth: 1,
      borderColor: '#333',
      paddingVertical: Math.min(15, SCREEN_WIDTH * 0.035),
      paddingHorizontal: Math.min(20, SCREEN_WIDTH * 0.04),
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
      marginLeft: 10,
      opacity: 0.7,
    },
    inviteFriendsButtonText: {
      color: '#aaa',
      fontSize: Math.min(16, SCREEN_WIDTH * 0.04),
      fontWeight: 'bold',
      textAlign: 'center',
    },
    contentContainer: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 80,
      minHeight: height - 150,
      alignItems: 'center',
    },
    // Add these styles to your existing styles object

// Results screen styles
// -------------------
sparkleIcon: {
  fontSize: 38,
  marginBottom: 10,
  color: '#FFFFFF',
},
resultsTitle: {
  fontSize: 26,
  fontWeight: 'bold',
  color: '#FFFFFF',
  textAlign: 'center',
  marginBottom: 15,
},
scoreCircleContainer: {
  alignItems: 'center',
  marginVertical: 15,
},
scoreCircle: {
  width: 100,
  height: 100,
  borderRadius: 50,
  backgroundColor: 'rgba(255,255,255,0.2)',
  justifyContent: 'center',
  alignItems: 'center',
  borderWidth: 2,
  borderColor: '#FFFFFF',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
},
scoreValue: {
  fontSize: 32,
  fontWeight: 'bold',
  color: '#FFFFFF',
},
scorePercent: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#FFFFFF',
},
scoreLabel: {
  fontSize: 14,
  color: '#FFFFFF',
  textTransform: 'uppercase',
  letterSpacing: 1,
},
imagesComparisonContainer: {
  flexDirection: 'row',
  justifyContent: 'center',
  alignItems: 'center',
  marginBottom: 25,
},
circularProfileImage: {
  width: 90,
  height: 90,
  borderRadius: 45,
  borderWidth: 3,
  borderColor: '#FFFFFF',
  backgroundColor: '#222222',
},
heartContainer: {
  marginHorizontal: 20,
},
heartIcon: {
  fontSize: 36,
  textShadowColor: 'rgba(0, 0, 0, 0.5)',
  textShadowOffset: { width: 1, height: 1 },
  textShadowRadius: 5,
},
insightsContainer: {
  backgroundColor: '#111111',
  borderRadius: 15,
  padding: 15,
  marginHorizontal: 15,
  marginBottom: 25,
  borderWidth: 1,
  borderColor: '#333333',
},
insightsTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
  marginBottom: 15,
  textAlign: 'center',
},
insightItem: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#1A1A1A',
  padding: 12,
  borderRadius: 10,
  marginBottom: 10,
},
insightIcon: {
  fontSize: 18,
  marginRight: 10,
},
insightText: {
  color: '#FFFFFF',
  fontSize: 16,
  flex: 1,
},
lockedInsightItem: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#1A1A1A',
  padding: 12,
  borderRadius: 10,
  opacity: 0.7,
},
lockedInsightText: {
  color: '#BBBBBB',
  fontSize: 16,
  flex: 1,
  fontStyle: 'italic',
},
analysisTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#FFFFFF',
  textAlign: 'center',
  marginTop: 10,
  marginBottom: 20,
},
blurredCategories: {
  backgroundColor: '#111111',
  borderRadius: 15,
  padding: 15,
  marginHorizontal: 15,
  marginBottom: 15,
  borderWidth: 1,
  borderColor: '#333333',
},
categoryRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  marginBottom: 15,
},
categoryColumn: {
  width: '48%',
},
categoryTitleSmall: {
  fontSize: 14,
  fontWeight: 'bold',
  color: '#DDDDDD',
  marginBottom: 8,
},
blurredScoreContainer: {
  marginBottom: 8,
},
blurredScore: {
  alignItems: 'center',
  justifyContent: 'center',
  height: 40,
  backgroundColor: '#1A1A1A',
  borderRadius: 8,
  position: 'relative',
  overflow: 'hidden',
},
hiddenScoreText: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#FFFFFF',
  opacity: 0.1,
},
fakeBlurOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(26, 26, 26, 0.7)',
  backdropFilter: 'blur(5px)',
},
scoreProgressBar: {
  height: 6,
  backgroundColor: '#333333',
  borderRadius: 3,
  overflow: 'hidden',
},
scoreProgress: {
  height: '100%',
  borderRadius: 3,
},
lockOverlayContainer: {
  alignItems: 'center',
  justifyContent: 'center',
  marginVertical: 25,
},
lockOverlayIcon: {
  fontSize: 42,
  color: '#FFFFFF',
  marginBottom: 10,
},
lockOverlayText: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
  textAlign: 'center',
},
benefitsContainer: {
  backgroundColor: '#111111',
  borderRadius: 15,
  padding: 20,
  marginHorizontal: 15,
  marginBottom: 25,
  borderWidth: 1,
  borderColor: '#333333',
},
benefitsTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
  marginBottom: 15,
  textAlign: 'center',
},
benefitItem: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 12,
},
benefitIcon: {
  fontSize: 16,
  color: '#4ECDC4',
  marginRight: 10,
  fontWeight: 'bold',
},
benefitText: {
  color: '#FFFFFF',
  fontSize: 16,
},
actionsButtonContainer: {
  marginHorizontal: 15,
  marginBottom: 30,
},
getProButton: {
  backgroundColor: '#6C63FF',
  paddingVertical: 15,
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: 12,
  marginBottom: 10,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 6,
},
buttonText: {
  color: '#FFFFFF',
  fontSize: 18,
  fontWeight: 'bold',
},
inviteFriendsButton: {
  backgroundColor: '#222222',
  paddingVertical: 15,
  alignItems: 'center',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#444444',
},
inviteFriendsButtonText: {
  color: '#FFFFFF',
  fontWeight: '600',
},
testimonialsContainer: {
  marginHorizontal: 15,
  marginBottom: 30,
},
testimonialsTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
  marginBottom: 15,
},
testimonialCard: {
  backgroundColor: '#111111',
  borderRadius: 12,
  padding: 15,
  marginBottom: 10,
  borderWidth: 1,
  borderColor: '#333333',
},
testimonialText: {
  color: '#DDDDDD',
  fontSize: 16,
  fontStyle: 'italic',
  lineHeight: 22,
},
testimonialAuthor: {
  color: '#999999',
  fontSize: 14,
  marginTop: 10,
  textAlign: 'right',
},
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0, 0, 0, 0.8)',
  justifyContent: 'center',
  alignItems: 'center',
},
modalContainer: {
  backgroundColor: '#1E2124',
  borderRadius: 20,
  padding: 20,
  width: SCREEN_WIDTH * 0.9,
  alignItems: 'center',
},
modalTitle: {
  color: COLORS.dark,
  fontSize: 24,
  fontWeight: 'bold',
  marginBottom: 10,
  textAlign: 'center',
},
modalSubtitle: {
  color: COLORS.dark,
  fontSize: 16,
  marginBottom: 20,
  textAlign: 'center',
},

modalButtonContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: '100%',
},
modalButton: {
  backgroundColor: COLORS.primary,
  padding: 12,
  borderRadius: 10,
  flex: 1,
  marginHorizontal: 5,
  alignItems: 'center',
},
modalButtonText: {
  color: COLORS.dark,
  fontSize: 16,
  fontWeight: 'bold',
},
copyIcon: {
  fontSize: 24,
},
shareButton: {
  backgroundColor: COLORS.primary,
  padding: 15,
  borderRadius: 10,
  width: '100%',
  alignItems: 'center',
  marginBottom: 10,
},
shareButtonText: {
  color: COLORS.dark,
  fontSize: 18,
  fontWeight: 'bold',
},
closeModalButton: {
  padding: 10,
},
closeModalText: {
  color: COLORS.danger,
  fontSize: 16,
},
// Styles to add to your getStyles function in Styles.js
referralPageContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  paddingHorizontal: 20,
  paddingVertical: 40,
  backgroundColor: '#000',
  width: '100%',
},
referralPageTitle: {
  fontSize: Math.min(22, SCREEN_WIDTH * 0.055),
  textAlign: 'center',
  color: COLORS.dark, // Bu COLORS.dark beyaz renk olduğu için (dark mode)
  fontWeight: 'bold',
  marginBottom: Math.min(30, SCREEN_WIDTH * 0.08),
  width: '90%',
},
referralInput: {
  backgroundColor: '#2C2F33',
  color: COLORS.dark,
  borderRadius: 10,
  padding: Math.min(15, SCREEN_WIDTH * 0.04),
  width: '100%',
  marginBottom: Math.min(40, SCREEN_WIDTH * 0.1),
  textAlign: 'center',
  fontSize: Math.min(16, SCREEN_WIDTH * 0.04),
},
referralContinueButton: {
  backgroundColor: '#6C63FF', // Mor renk
  paddingVertical: 12,
  paddingHorizontal: 40,
  borderRadius: 10,
  width: 280, // Görsele uygun sabit genişlik
  alignItems: 'center',
  justifyContent: 'center',
},
referralContinueButtonText: {
  color: '#FFFFFF',
  fontSize: 18,
  fontWeight: 'bold',
  textAlign: 'center',
},
  });

export default getStyles;